name: 'My Custom JavaScript Action'
description: 'Description of my custom action'
inputs:
  exampleInput:
    description: 'An example input'
    required: true
runs:
  using: 'node12'
  main: 'action/index.js'